name: Build QuickJS Static Library

on:
  workflow_dispatch:

jobs:
  build:
    name: Build QuickJS Static Library
    strategy:
        fail-fast: false
        matrix:
            platform: [ubuntu-18.04, macos-11]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: true
          fetch-depth: 1

    - name: Prebuild for linux
      if: matrix.platform == 'ubuntu-18.04'
      run: rm -rf deps/libs/linux* && cp -a deps/Makefile deps/quickjs
      
    - name: Pull Images
      if: matrix.platform == 'ubuntu-18.04'
      run: docker pull gcc && docker pull aarch64-linux-gnu
    
    - name: Build linux amd64
      if: matrix.platform == 'ubuntu-18.04'
      run: mkdir deps/libs/linux_amd64 && cd deps/quickjs && docker run --rm -v $(pwd):/home gcc /bin/bash -c "cd /home && make clean && make libquickjs.a "  && mv libquickjs.a ../libs/linux_amd64

    - name: Build linux arm64
      if: matrix.platform == 'ubuntu-18.04'
      run: mkdir deps/libs/linux_arm64 && cd deps/quickjs && docker run --rm -v $(pwd):/workdir -e CROSS_TRIPLE=aarch64-linux-gnu multiarch/crossbuild /bin/bash -c "cd /workdir && make clean && make libquickjs.a "  && mv libquickjs.a ../libs/linux_arm64

      
    - name: Prebuild for mac
      if: matrix.platform == 'macos-11'
      run: rm -rf deps/libs/darwin_* && cp -a deps/Makefile deps/quickjs

    - name: Build darwin amd64 
      if: matrix.platform == 'macos-11'
      run: mkdir deps/libs/darwin_amd64 && cd deps/quickjs && make clean && make libquickjs.a && mv libquickjs.a ../libs/darwin_amd64

    - name: Build darwin arm64 
      if: matrix.platform == 'macos-11'
      run: mkdir deps/libs/darwin_arm64 && cd deps/quickjs && make clean && make -e CONFIG_DARWIN_ARM64=y libquickjs.a && mv libquickjs.a ../libs/darwin_arm64
      
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update QuickJS Static Library ${{ matrix.platform }}
        branch-suffix: random
        delete-branch: true
        title: Update QuickJS Static library ${{ matrix.platform }}
