name: Build QuickJS Static library

on:
  workflow_dispatch:


jobs:
  build:

    name: Build QuickJS for ${{ matrix.platform }} ${{ matrix.arch }}
    strategy:
        fail-fast: false
        matrix:
            platform: [ubuntu-18.04, macos-11]
            arch: [x86_64]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: true
          fetch-depth: 1
          
    - name: Build QuickJS linux
      if: matrix.platform == 'ubuntu-18.04'
      run: rm -rf deps/libs/linux_x86_64 && mkdir deps/libs/linux_x86_64 && cd deps/quickjs && make && mv *.a ../libs/linux_x86_64
      
    - name: Build QuickJS MAC
      if: matrix.platform == 'macos-11'
      run: rm -rf deps/libs/darwin_amd64 && mkdir deps/libs/darwin_amd64 && cd deps/quickjs && make && mv *.a ../libs/darwin_amd64

    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update QuickJS static library for ${{ matrix.platform }} ${{ matrix.arch }}
        branch-suffix: random
        delete-branch: true
        title: QuickJS static library for ${{ matrix.platform }} ${{ matrix.arch }}
